# Generated by Django 5.2.4 on 2025-07-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=5)),
                ('category', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
